### ISSUE TITLE
Dark Theme Issue

### ISSUE THREAD

**Issue by msayan** [estmob/SendAnywhere-Android-UI-SDK#2]
Hello,

We as General Mobile use this sdk in our apps ( File Manager, Music Player) and we have issue with dark theme. Screen shots :
When Receiving : 
![screenshot_20170705-125749](https://user-images.githubusercontent.com/10603846/27859681-34dc5d1a-6182-11e7-8374-695c84e805af.png)
When Sending :
![screenshot_20170705-125810](https://user-images.githubusercontent.com/10603846/27859680-34da9d4a-6182-11e7-9876-6addd0adf204.png)
When Click Cancel :
![screenshot_20170705-125817](https://user-images.githubusercontent.com/10603846/27859679-34d9300e-6182-11e7-9093-1db23157bd82.png)

**Comment by kyujin-sah** [comment]
We fixed this problem. Try the latest version of the SDK. Thank you.

**Comment by msayan** [comment]
Thanks .
